name: release-gtag-react

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/pullrequest-gtag-react.yml
      - packages/gtag-react/*

defaults:
  run:
    working-directory: packages/gtag-react

jobs:
  pullrequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install package
        run: npm ci --ignore-scripts
      - name: test
        run: npm test
      - name: build
        run: npm run build --if-present
