name: release-gtag

on:
  push:
    paths:
      - packages/gtag/package.json

defaults:
  run:
    working-directory: packages/gtag

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install package
        run: npm ci --ignore-scripts
      - name: test
        run: npm test
      - name: build
        run: npm run build --if-present
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}